services:
  # バックエンドサーバー
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5000"  # 外部ポートを5001に変更
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=autodialer
      - MOCK_ASTERISK=true
    depends_on:
      - mysql
    networks:
      - autodialer-network

  # データベース
  mysql:
    image: mysql:8.0
    platform: linux/arm64
    ports:
      - "13306:3306"  # 外部ポートは13306のまま
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=autodialer
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - autodialer-network

networks:
  autodialer-network:
    driver: bridge

volumes:
  mysql_data:
