services:
  # バックエンドサーバー
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5000"  # 外部ポートを5001に変更
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: autodialer
      # モックモードを無効化してTwilioを使用
      MOCK_ASTERISK: "true"
      USE_TWILIO: "false"
      PUBLIC_URL: ${PUBLIC_URL}
      LANG: "ja_JP.UTF-8"
      LC_ALL: "ja_JP.UTF-8"
      USE_SIMPLE_AUTH: "false"
      USE_MOCK_DATA: "false"
    depends_on:
      - mysql
    networks:
      - autodialer-network

  # フロントエンドサーバー（変更なし）
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3000"  # 外部ポートを3003に変更
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: "http://152.42.200.112:5001/api"
      REACT_APP_USE_MOCK_DATA: "false"
      CHOKIDAR_USEPOLLING: "true"
      WDS_SOCKET_HOST: localhost
      WDS_SOCKET_PORT: 3003
      DANGEROUSLY_DISABLE_HOST_CHECK: true  # 開発環境のみ
      PORT : 3000
      HOST: "0.0.0.0"
    depends_on:
      - backend
    networks:
      - autodialer-network

  # データベース（変更なし）
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: autodialer
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --init-connect='SET NAMES utf8mb4'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    networks:
      - autodialer-network

networks:
  autodialer-network:
    driver: bridge

volumes:
  mysql_data:
