version: '3.8'

services:
  # バックエンドサーバー
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev  # 本番用のDockerfileがあれば変更
    ports:
      - "5000:5000"  # 標準ポートに戻す
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: production
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_DATABASE: autodialer
    env_file:
      - ./backend/.env.production
    depends_on:
      - mysql
    networks:
      - autodialer-network
    restart: unless-stopped  # 自動再起動設定

  # フロントエンドサーバー
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  # 本番用のDockerfileがあれば変更
    ports:
      - "3000:3000"  # 標準ポートに戻す
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: production
      REACT_APP_API_URL: /api  # Nginxプロキシ経由でアクセス
      PORT: 3000
      HOST: "0.0.0.0"
    env_file:
      - ./frontend/.env.production
    depends_on:
      - backend
    networks:
      - autodialer-network
    restart: unless-stopped

  # データベース
  mysql:
    image: mysql:8.0
    platform: linux/amd64  # DigitalOceanはx86_64なのでarm64を削除
    ports:
      - "127.0.0.1:3306:3306"  # ローカルホストのみにバインド
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}  # 環境変数から読み込み
      MYSQL_DATABASE: autodialer
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --init-connect='SET NAMES utf8mb4'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    networks:
      - autodialer-network
    restart: unless-stopped

  # Nginxリバースプロキシ（新規追加）
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - nginx_certs:/etc/nginx/certs:ro
      - nginx_html:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - autodialer-network
    restart: unless-stopped

networks:
  autodialer-network:
    driver: bridge

volumes:
  mysql_data:
  nginx_certs:
  nginx_html:
