services:
  # データベース（healthcheckを追加）
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: autodialer
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --init-connect='SET NAMES utf8mb4'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    networks:
      - autodialer-network
    # 以下のhealthcheckセクションを追加
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 5s
      retries: 10
      interval: 5s

  # バックエンドサーバー（depends_onを修正）
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: autodialer
      MOCK_ASTERISK: "true"
      USE_TWILIO: "false"
      PUBLIC_URL: ${PUBLIC_URL}
      LANG: "ja_JP.UTF-8"
      LC_ALL: "ja_JP.UTF-8"
      USE_SIMPLE_AUTH: "true"  # 認証を簡略化
      USE_MOCK_DATA: "true"    # モックデータを使用
      # ヘルスチェックのための待機時間を設定
      WAIT_HOSTS: mysql:3306
      WAIT_TIMEOUT: 60
    # 修正：mysqlがhealthcheckに合格するまで待機
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - autodialer-network
    # 再起動ポリシーを追加
    restart: unless-stopped

  # フロントエンドサーバー（APIエンドポイントを修正）
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      # APIのURLを修正（localhostを使用）
      REACT_APP_API_URL: "http://localhost:5001/api"
      REACT_APP_USE_MOCK_DATA: "true"  # モックデータを使用
      CHOKIDAR_USEPOLLING: "true"
      WDS_SOCKET_HOST: localhost
      WDS_SOCKET_PORT: 3003
      DANGEROUSLY_DISABLE_HOST_CHECK: true
      PORT: 3000
      HOST: "0.0.0.0"
    depends_on:
      - backend
    networks:
      - autodialer-network
    # 再起動ポリシーを追加
    restart: unless-stopped

networks:
  autodialer-network:
    driver: bridge

volumes:
  mysql_data: