services:
  # データベース
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: autodialer
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      TZ: Asia/Tokyo
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --init-connect='SET NAMES utf8mb4'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - autodialer-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 5s
      retries: 10
      interval: 5s

  # バックエンドサーバー（実動作版）
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5000"
      - "5060:5060/udp"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /etc/localtime:/etc/localtime:ro
    environment:
      NODE_ENV: development
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: autodialer
      # 実動作モード（モックなし）
      MOCK_SIP: "false"
      MOCK_ASTERISK: "false"
      USE_TWILIO: "false"
      PUBLIC_URL: ${PUBLIC_URL}
      LANG: "ja_JP.UTF-8"
      LC_ALL: "ja_JP.UTF-8"
      USE_SIMPLE_AUTH: "true"
      USE_MOCK_DATA: "false"
      WAIT_HOSTS: mysql:3306
      WAIT_TIMEOUT: 60
      TZ: Asia/Tokyo
      # 音声エラー無効化
      ALSA_LOG_LEVEL: "0"
      PULSE_LOG_LEVEL: "0"
      # SIP設定
      DEFAULT_CALL_PROVIDER: "sip"
      SIP_SERVER: "ito258258.site"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - autodialer-network
    restart: unless-stopped

  # フロントエンドサーバー
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /etc/localtime:/etc/localtime:ro
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: "http://localhost:5001/api"
      REACT_APP_USE_MOCK_DATA: "false"
      CHOKIDAR_USEPOLLING: "true"
      WDS_SOCKET_HOST: localhost
      WDS_SOCKET_PORT: 3003
      DANGEROUSLY_DISABLE_HOST_CHECK: true
      PORT: 3000
      HOST: "0.0.0.0"
      TZ: Asia/Tokyo
    depends_on:
      - backend
    networks:
      - autodialer-network
    restart: unless-stopped

networks:
  autodialer-network:
    driver: bridge

volumes:
  mysql_data: