FROM node:18-alpine

WORKDIR /app

# パッケージインストール用ファイルのみコピー
COPY package*.json ./

# 通常のnpm installを使用して依存関係をインストール
RUN npm install

# nodemonをグローバルにインストール
RUN npm install -g nodemon

# アプリケーションのポートを公開
EXPOSE 5000

# 開発モードで起動
CMD ["nodemon", "src/index.js"]